### ISSUE TITLE
Scrollbar styling (globally or util class)

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#122]
We [currently](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/plugins/tailwind.cjs#L13-L22) have (`.scrollbar-none`) to completely hide the scrollbar, but it would be nice to also have some better styling (possibly globally, but  at least opt-in).

Styling the scrollbar is setting:
- `::-webkit-scrollbar`
- `::-webkit-scrollbar-thumb`
- `::-webkit-scrollbar-track`

on Chrome/Safari, and
- `scrollbar-color`
- `scrollbar-width`

on Firefox.

See docs for reference and additional properties
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling
- https://css-tricks.com/almanac/properties/s/scrollbar/

I have an old [REPL](https://svelte.dev/repl/59e42e69f1484aba972c7bb54197415a?version=4.2.3) that can also be used as reference.
```css
.scrollContainer {
	scrollbar-color: var(--scrollcolor) var(--scrollbackground);
}
.scrollContainer::-webkit-scrollbar {
	height: 0.5rem;
	width: 0.5rem;
	border-radius: 1rem;
	background: var(--scrollbackground);
}

.scrollContainer::-webkit-scrollbar-thumb {
	border-radius: 1rem;
	background: var(--scrollcolor);
}

.scrollContainer::-webkit-scrollbar-track {
	border-radius: 1rem;
	background: var(--scrollbackground);
}
```
