### ISSUE TITLE
Docs regarding Tailwind v4

### ISSUE THREAD

**Issue by 0xmiki** [techniq/svelte-ux#606]
First off, I want to thank you for all your hard work creating this awesome library and also the chart library which I am really looking forward to using.

It looks like tailwind v4.1 doesn't have a config file anymore they depricated it and will only use the app.css file 

It would be great if this library had support for tailwind v4.1 out of the gate, since as of right now tailwind v4 is what gets installed for users by default. Svelte-ux's docs is based around the config file which no longer exists and could create confusion for a lot of people. I suggest that until tihs library supports v4, to add a banner in the docs telling users to use it with the compatible tailwind version (v3) which has tailwind.config.cjs file. 

I attempted to add the layerStack and the content path by doing: 

@plugin "@layerstack/tailwind/plugin";
@source "./node_modules/svelte-ux/**/*.{svelte,js}";

in the css file but that was not succesful in my attempt

https://github.com/tailwindlabs/tailwindcss/discussions/15820
https://tailwindcss.com/blog/tailwindcss-v4#css-first-configuration

**Comment by techniq** [comment]
Hey @0xmiki 👋, thanks for the kind words.

Svelte UX actually already has support for Tailwind 4.x on the `@next` releases 😁 (added in [svelte-ux@2.0.0-next.0](https://github.com/techniq/svelte-ux/releases/tag/svelte-ux%402.0.0-next.0).  `2.0.0` will also include a fully migration to Svelte 5 syntax (state runes, snippets, etc) but I haven't started this work yet (I hope to soon).

Sadly the documentation always lags behind, but the quick instructions:

- Use `@next` packages for Svelte UX, LayerStack, and LayerChart for full Tailwind 4.x support
- Remove your `tailconfig.config.js` (or at least the LayerStack plugin) and replace with the following in `app.css`

```css
@import 'tailwindcss';

@import '@layerstack/tailwind/core.css';
@import '@layerstack/tailwind/utils.css';
@import '@layerstack/tailwind/themes/basic.css';

@source '../../node_modules/svelte-ux/dist';
@source '../../node_modules/layerchart/dist';

:root {
  --color-primary: var(--color-emerald-600);
  --color-secondary: var(--color-blue-500);
}
```

`@layerstack/tailwind` (the theme system used by Svelte UX) was migrated to be css-only.  You can see the source on the next branch [here](https://github.com/techniq/layerstack/tree/next/packages/tailwind/src/lib/css)

You can customize your theme as you see fit using CSS variables.  Dark mode is targeted using with `.dark` class on `:root`/`<html>`


```css
:root {
  --color-primary: var(--color-purple-700);
  --color-secondary: var(--color-orange-500);

  &.dark {
    --color-primary: var(--color-purple-400);
    --color-surface-100: var(--color-zinc-900);
    --color-surface-200: var(--color-zinc-950);
    --color-surface-300: var(--color-black);
  }
}
```

This is for the basic light/dark themes.  If you want multiple light and dark themes and leverage the migrated Skeleton/Daisy UI themes, you can replace `@layerstack/tailwind/themes/basic.css` with `@layerstack/tailwind/themes/all.css` (this is what Svelte UX / etc use for their [docs](https://github.com/techniq/svelte-ux/blob/next/packages/svelte-ux/src/routes/app.css).

I have a few reference projects using this setup already (as well as my main work project).  Check out [Github Analysis](https://github.com/techniq/github-analysis) and [Strava Analysis](https://github.com/techniq/strava-analysis).

I hope to prioritize updating Svelte UX to Svelte 5 (like LayerChart was) and updating the docs.  I'm always open for PRs if you have any desire (especially for improving the docs).

I'll keep this issue open until the docs are updated.  Have a great day!
